// This file is the committed placeholder; the actual `environment.ts` is
// generated by scripts/write-env.mjs from frontend/.env (and is gitignored).

export const environment = {
  supabaseUrl: '__SUPABASE_URL__',
  supabaseAnonKey: '__SUPABASE_ANON_KEY__',
  apiBaseUrl: '__API_BASE_URL__',
};
